SELECT *
FROM (SELECT DATE_FORMAT(SALES_DATE, '%Y-%m-%d') AS SALES_DATE, PRODUCT_ID, USER_ID, SALES_AMOUNT
    FROM ONLINE_SALE 
    WHERE SALES_DATE LIKE '2022-03%'
    UNION ALL
    SELECT SALES_DATE, PRODUCT_ID, NULL AS USER_ID, SALES_AMOUNT
    FROM OFFLINE_SALE 
    WHERE SALES_DATE LIKE '2022-03%') UNION_TABLE
ORDER BY UNION_TABLE.SALES_DATE, UNION_TABLE.PRODUCT_ID, UNION_TABLE.USER_ID;