SELECT FLAVOR
FROM (SELECT FLAVOR, SUM(TOTAL_ORDER) AS TOTAL_ORDER
      FROM (SELECT FLAVOR, TOTAL_ORDER FROM FIRST_HALF
            UNION ALL
            SELECT FLAVOR, TOTAL_ORDER FROM JULY) 
            AS UNION_TMP
      GROUP BY FLAVOR) 
      AS GROUP_TMP
ORDER BY TOTAL_ORDER DESC
LIMIT 3;
